# FlappyBird - Random Agent

In this notebook, we will implement a random agent that will play FlappyBird.

## Index

- [1. Initial Setup](#1.-Initial-Setup)
- [2. Check the Gym environment](#2.-Check-the-Gym-environment)
- [3. Define custom functions](#3.-Define-custom-functions)
- [4. Training the RL agent](#4.-Training-the-RL-agent)
- [5. Play the game](#5.-Play-the-game)

## 1. Initial Setup

Add project root directory to the path.

In [4]:
import sys
from pathlib import Path

if str(Path(".").absolute().parent) not in sys.path:
    sys.path.append(str(Path(".").absolute().parent))

Imports modules

In [8]:
import numpy as np
import flappy_bird_gym

from src.base import Agent
from src.utils import play_env

## 2. Check the Gym environment

Before we start, we need to check how the environment works. For this, we will check the action space and observation space.

In [6]:
env = flappy_bird_gym.make("FlappyBird-rgb-v0")

action_size = env.action_space.n
state_size = env.observation_space.shape[0]

print(f"Number of actions: {action_size}")
print(f"Sample state shape: {env.reset().shape}")
print(f"Sample state: {env.reset()}")

Number of actions: 2
Sample state shape: (288, 512, 3)
Sample state: [[[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [222 216 149]
  [222 216 149]
  [222 216 149]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [222 216 149]
  [222 216 149]
  [222 216 149]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [222 216 149]
  [222 216 149]
  [222 216 149]]

 ...

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [222 216 149]
  [222 216 149]
  [222 216 149]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [222 216 149]
  [222 216 149]
  [222 216 149]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [222 216 149]
  [222 216 149]
  [222 216 149]]]


## 3. Define custom functions

In the next cell, we define a `custom_prep_state()` function that will be used to preprocess the state of the game.

We will replace the `prep_state()` function of the agent with this one.

In [9]:
def custom_prep_state(state: np.ndarray) -> np.ndarray:
    #return state # No preprocessing
    return state.ravel() # Flatten

sample_state = custom_prep_state(env.reset())
print(f"Shape of state: {sample_state.shape}")
sample_state

Shape of state: (442368,)


array([200, 200, 200, ..., 222, 216, 149], dtype=uint8)

## 4. Training the RL agent

Firstly, we will instantiate the AgentConfig that defines the hyperparameters of our Dueling DQN Agent.

In [10]:
agent = Agent(state_size=len(sample_state),
              action_size=env.action_space.n, seed=1993)

## 5. Play the game

In [12]:
play_env(agent, env, render=True)

Score: 101
